name: App CI/CD

on:
  workflow_call:
    inputs:
      app-name:
        description: "Name of the image/app"
        required: false
        default: ${{ github.repository }}
        type: string
      appid:
        description: "Application ID"
        required: false
        default: "0"
        type: string
      orgid:
        description: "Organization ID"
        required: false
        default: "0"
        type: string
      buid:
        description: "Business Unit ID"
        required: false
        default: "0"
        type: string
      test-directory:
        description: "Directory containing tests"
        required: false
        default: "test"
        type: string
      sonar-source-path:
        description: "Path to the source code for SonarQube scan"
        required: false
        default: "src"
        type: string
      region:
        description: "Region"
        required: false
        default: "us-east-1"
        type: string
    secrets:
      role-to-assume:
        description: "Role to assume"
        required: true
        type: string

jobs:
  secrets-check:
    name: Secrets Check
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Secrets Check
        uses: orbitcluster/oc-cicd-secretscanner-workflow@v2
        with:
          github-token: ${{ github.token }}

  sonarqube-check:
    name: SonarQube Check
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: SonarQube Check
        uses: orbitcluster/oc-cicd-sonarscan-workflow@v1
        with:
          sonar-source-path: ${{ inputs.sonar-source-path }}

  sast-scan:
    name: SAST Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: SAST Scan
        uses: orbitcluster/oc-cicd-sast-workflow@v1
        with:
          language: python

  docker-build-push:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [secrets-check, sonarqube-check, sast-scan]
    env:
      DOCKER_TAG: ""
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Docker Build
        uses: orbitcluster/oc-cicd-docker-build-workflow@v1
        with:
          docker-build-path: .
          image-name: ${{ inputs.app-name }}
          appid: ${{ inputs.appid }}
          orgid: ${{ inputs.orgid }}
          buid: ${{ inputs.buid }}

      - name: Docker Push
        id: docker-push
        uses: orbitcluster/oc-cicd-docker-push-workflow@feat/push_init
        with:
          image-type: docker
          image-name: ${{ inputs.app-name }}
          tag: ${{ env.DOCKER_TAG }}
          appid: ${{ inputs.appid }}
          orgid: ${{ inputs.orgid }}
          buid: ${{ inputs.buid }}
          role-to-assume: ${{ secrets.role-to-assume }}
