name: App CI/CD

on:
  workflow_call:
    inputs:
      app-name:
        description: "Name of the image/app"
        required: false
        default: ${{ github.repository }}
        type: string
      appid:
        description: "Application ID"
        required: false
        default: "0"
        type: string
      orgid:
        description: "Organization ID"
        required: false
        default: "0"
        type: string
      buid:
        description: "Business Unit ID"
        required: false
        default: "0"
        type: string
      test-directory:
        description: "Directory containing tests"
        required: false
        default: "test"
        type: string
      sonar-source-path:
        description: "Path to the source code for SonarQube scan"
        required: false
        default: "src"
        type: string
      region:
        description: "Region"
        required: false
        default: "us-east-1"
        type: string
    secrets:
      role-to-assume:
        description: "Role to assume"
        required: true

jobs:
  secrets-check:
    name: Secrets Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Secrets Check
        uses: orbitcluster/oc-cicd-secretscanner-workflow@v2
        with:
          github-token: ${{ github.token }}

  sonarqube-check:
    name: SonarQube Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: SonarQube Check
        uses: orbitcluster/oc-cicd-sonarscan-workflow@v1
        with:
          sonar-source-path: ${{ inputs.sonar-source-path }}

  sast-scan:
    name: SAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: SAST Scan
        uses: orbitcluster/oc-cicd-sast-workflow@v1
        with:
          language: python

  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.release-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Semantic Version
        id: semver
        uses: orbitcluster/oc-cicd-release-workflow@v1
        with:
          dry-run: ${{ github.ref_name != 'main' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  docker-build-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: [secrets-check, sonarqube-check, sast-scan, semantic-release]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Docker Build
        id: docker-build
        if: ${{ github.event.action != 'closed' }}
        uses: orbitcluster/oc-cicd-docker-build-workflow@v1
        with:
          docker-build-path: .
          image-name: ${{ inputs.app-name }}
          tag-override: ${{ github.ref_name == 'main' && needs.semantic-release.outputs.version || '' }}
          appid: ${{ inputs.appid }}
          orgid: ${{ inputs.orgid }}
          buid: ${{ inputs.buid }}
          build-image: ${{ github.event.action != 'closed' }}

      - name: Docker Push
        id: docker-push
        if: ${{ github.event.action != 'closed' }}
        uses: orbitcluster/oc-cicd-docker-push-workflow@v1
        with:
          image_type: docker
          image-name: ${{ inputs.app-name }}
          tag: ${{ steps.docker-build.outputs.docker-tag }}
          appid: ${{ inputs.appid }}
          orgid: ${{ inputs.orgid }}
          buid: ${{ inputs.buid }}
          role-to-assume: ${{ secrets.role-to-assume }}
          action_type: push
          branch-name: ${{ steps.docker-build.outputs.safe-branch }}

      - name: Docker Cleanup
        id: docker-cleanup
        if: ${{ github.event.action == 'closed' }}
        uses: orbitcluster/oc-cicd-docker-push-workflow@v1
        with:
          image_type: docker
          image-name: ${{ inputs.app-name }}
          tag: ${{ steps.docker-build.outputs.docker-tag }}
          appid: ${{ inputs.appid }}
          orgid: ${{ inputs.orgid }}
          buid: ${{ inputs.buid }}
          role-to-assume: ${{ secrets.role-to-assume }}
          action_type: cleanup
          branch-name: ${{ steps.docker-build.outputs.safe-branch }}
